/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutContactsRouteImport } from './routes/_layout/contacts'
import { Route as LayoutDomainsRouteImport } from './routes/_layout/domains'
import { Route as LayoutRegistrarsRouteImport } from './routes/_layout/registrars'
import { Route as LayoutSessionsRouteImport } from './routes/_layout/sessions'
import { Route as LayoutTransactionsRouteImport } from './routes/_layout/transactions'
import { Route as LayoutZonesRouteImport } from './routes/_layout/zones'
import { Route as LayoutContactsContactIdRouteImport } from './routes/_layout/contacts/$contactId'
import { Route as LayoutDomainsDomainIdRouteImport } from './routes/_layout/domains/$domainId'
import { Route as LayoutSessionsSessionIdRouteImport } from './routes/_layout/sessions/$sessionId'
import { Route as LayoutTransactionsTransactionIdRouteImport } from './routes/_layout/transactions/$transactionId'
import { Route as LayoutZonesZoneIdRouteImport } from './routes/_layout/zones/$zoneId'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactsRoute = LayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDomainsRoute = LayoutDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRegistrarsRoute = LayoutRegistrarsRouteImport.update({
  id: '/registrars',
  path: '/registrars',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSessionsRoute = LayoutSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTransactionsRoute = LayoutTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutZonesRoute = LayoutZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactsContactIdRoute = LayoutContactsContactIdRouteImport.update({
  id: '/$contactId',
  path: '/$contactId',
  getParentRoute: () => LayoutContactsRoute,
} as any)
const LayoutDomainsDomainIdRoute = LayoutDomainsDomainIdRouteImport.update({
  id: '/$domainId',
  path: '/$domainId',
  getParentRoute: () => LayoutDomainsRoute,
} as any)
const LayoutSessionsSessionIdRoute = LayoutSessionsSessionIdRouteImport.update({
  id: '/$sessionId',
  path: '/$sessionId',
  getParentRoute: () => LayoutSessionsRoute,
} as any)
const LayoutTransactionsTransactionIdRoute =
  LayoutTransactionsTransactionIdRouteImport.update({
    id: '/$transactionId',
    path: '/$transactionId',
    getParentRoute: () => LayoutTransactionsRoute,
  } as any)
const LayoutZonesZoneIdRoute = LayoutZonesZoneIdRouteImport.update({
  id: '/$zoneId',
  path: '/$zoneId',
  getParentRoute: () => LayoutZonesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/contacts': typeof LayoutContactsRouteWithChildren
  '/domains': typeof LayoutDomainsRouteWithChildren
  '/registrars': typeof LayoutRegistrarsRoute
  '/sessions': typeof LayoutSessionsRouteWithChildren
  '/transactions': typeof LayoutTransactionsRouteWithChildren
  '/zones': typeof LayoutZonesRouteWithChildren
  '/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/domains/$domainId': typeof LayoutDomainsDomainIdRoute
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/transactions/$transactionId': typeof LayoutTransactionsTransactionIdRoute
  '/zones/$zoneId': typeof LayoutZonesZoneIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/contacts': typeof LayoutContactsRouteWithChildren
  '/domains': typeof LayoutDomainsRouteWithChildren
  '/registrars': typeof LayoutRegistrarsRoute
  '/sessions': typeof LayoutSessionsRouteWithChildren
  '/transactions': typeof LayoutTransactionsRouteWithChildren
  '/zones': typeof LayoutZonesRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/domains/$domainId': typeof LayoutDomainsDomainIdRoute
  '/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/transactions/$transactionId': typeof LayoutTransactionsTransactionIdRoute
  '/zones/$zoneId': typeof LayoutZonesZoneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_layout/contacts': typeof LayoutContactsRouteWithChildren
  '/_layout/domains': typeof LayoutDomainsRouteWithChildren
  '/_layout/registrars': typeof LayoutRegistrarsRoute
  '/_layout/sessions': typeof LayoutSessionsRouteWithChildren
  '/_layout/transactions': typeof LayoutTransactionsRouteWithChildren
  '/_layout/zones': typeof LayoutZonesRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/contacts/$contactId': typeof LayoutContactsContactIdRoute
  '/_layout/domains/$domainId': typeof LayoutDomainsDomainIdRoute
  '/_layout/sessions/$sessionId': typeof LayoutSessionsSessionIdRoute
  '/_layout/transactions/$transactionId': typeof LayoutTransactionsTransactionIdRoute
  '/_layout/zones/$zoneId': typeof LayoutZonesZoneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/contacts'
    | '/domains'
    | '/registrars'
    | '/sessions'
    | '/transactions'
    | '/zones'
    | '/contacts/$contactId'
    | '/domains/$domainId'
    | '/sessions/$sessionId'
    | '/transactions/$transactionId'
    | '/zones/$zoneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/contacts'
    | '/domains'
    | '/registrars'
    | '/sessions'
    | '/transactions'
    | '/zones'
    | '/'
    | '/contacts/$contactId'
    | '/domains/$domainId'
    | '/sessions/$sessionId'
    | '/transactions/$transactionId'
    | '/zones/$zoneId'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/_layout/contacts'
    | '/_layout/domains'
    | '/_layout/registrars'
    | '/_layout/sessions'
    | '/_layout/transactions'
    | '/_layout/zones'
    | '/_layout/'
    | '/_layout/contacts/$contactId'
    | '/_layout/domains/$domainId'
    | '/_layout/sessions/$sessionId'
    | '/_layout/transactions/$transactionId'
    | '/_layout/zones/$zoneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts': {
      id: '/_layout/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof LayoutContactsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/domains': {
      id: '/_layout/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof LayoutDomainsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/registrars': {
      id: '/_layout/registrars'
      path: '/registrars'
      fullPath: '/registrars'
      preLoaderRoute: typeof LayoutRegistrarsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sessions': {
      id: '/_layout/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof LayoutSessionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/transactions': {
      id: '/_layout/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof LayoutTransactionsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/zones': {
      id: '/_layout/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof LayoutZonesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contacts/$contactId': {
      id: '/_layout/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof LayoutContactsContactIdRouteImport
      parentRoute: typeof LayoutContactsRoute
    }
    '/_layout/domains/$domainId': {
      id: '/_layout/domains/$domainId'
      path: '/$domainId'
      fullPath: '/domains/$domainId'
      preLoaderRoute: typeof LayoutDomainsDomainIdRouteImport
      parentRoute: typeof LayoutDomainsRoute
    }
    '/_layout/sessions/$sessionId': {
      id: '/_layout/sessions/$sessionId'
      path: '/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof LayoutSessionsSessionIdRouteImport
      parentRoute: typeof LayoutSessionsRoute
    }
    '/_layout/transactions/$transactionId': {
      id: '/_layout/transactions/$transactionId'
      path: '/$transactionId'
      fullPath: '/transactions/$transactionId'
      preLoaderRoute: typeof LayoutTransactionsTransactionIdRouteImport
      parentRoute: typeof LayoutTransactionsRoute
    }
    '/_layout/zones/$zoneId': {
      id: '/_layout/zones/$zoneId'
      path: '/$zoneId'
      fullPath: '/zones/$zoneId'
      preLoaderRoute: typeof LayoutZonesZoneIdRouteImport
      parentRoute: typeof LayoutZonesRoute
    }
  }
}

interface LayoutContactsRouteChildren {
  LayoutContactsContactIdRoute: typeof LayoutContactsContactIdRoute
}

const LayoutContactsRouteChildren: LayoutContactsRouteChildren = {
  LayoutContactsContactIdRoute: LayoutContactsContactIdRoute,
}

const LayoutContactsRouteWithChildren = LayoutContactsRoute._addFileChildren(
  LayoutContactsRouteChildren,
)

interface LayoutDomainsRouteChildren {
  LayoutDomainsDomainIdRoute: typeof LayoutDomainsDomainIdRoute
}

const LayoutDomainsRouteChildren: LayoutDomainsRouteChildren = {
  LayoutDomainsDomainIdRoute: LayoutDomainsDomainIdRoute,
}

const LayoutDomainsRouteWithChildren = LayoutDomainsRoute._addFileChildren(
  LayoutDomainsRouteChildren,
)

interface LayoutSessionsRouteChildren {
  LayoutSessionsSessionIdRoute: typeof LayoutSessionsSessionIdRoute
}

const LayoutSessionsRouteChildren: LayoutSessionsRouteChildren = {
  LayoutSessionsSessionIdRoute: LayoutSessionsSessionIdRoute,
}

const LayoutSessionsRouteWithChildren = LayoutSessionsRoute._addFileChildren(
  LayoutSessionsRouteChildren,
)

interface LayoutTransactionsRouteChildren {
  LayoutTransactionsTransactionIdRoute: typeof LayoutTransactionsTransactionIdRoute
}

const LayoutTransactionsRouteChildren: LayoutTransactionsRouteChildren = {
  LayoutTransactionsTransactionIdRoute: LayoutTransactionsTransactionIdRoute,
}

const LayoutTransactionsRouteWithChildren =
  LayoutTransactionsRoute._addFileChildren(LayoutTransactionsRouteChildren)

interface LayoutZonesRouteChildren {
  LayoutZonesZoneIdRoute: typeof LayoutZonesZoneIdRoute
}

const LayoutZonesRouteChildren: LayoutZonesRouteChildren = {
  LayoutZonesZoneIdRoute: LayoutZonesZoneIdRoute,
}

const LayoutZonesRouteWithChildren = LayoutZonesRoute._addFileChildren(
  LayoutZonesRouteChildren,
)

interface LayoutRouteChildren {
  LayoutContactsRoute: typeof LayoutContactsRouteWithChildren
  LayoutDomainsRoute: typeof LayoutDomainsRouteWithChildren
  LayoutRegistrarsRoute: typeof LayoutRegistrarsRoute
  LayoutSessionsRoute: typeof LayoutSessionsRouteWithChildren
  LayoutTransactionsRoute: typeof LayoutTransactionsRouteWithChildren
  LayoutZonesRoute: typeof LayoutZonesRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutContactsRoute: LayoutContactsRouteWithChildren,
  LayoutDomainsRoute: LayoutDomainsRouteWithChildren,
  LayoutRegistrarsRoute: LayoutRegistrarsRoute,
  LayoutSessionsRoute: LayoutSessionsRouteWithChildren,
  LayoutTransactionsRoute: LayoutTransactionsRouteWithChildren,
  LayoutZonesRoute: LayoutZonesRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
